language: ruby
rvm:
- 2.4.1

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

install:
- travis_retry bundle install

before_script:
  - memcached -p 11211 &
  - cp .env.travis .env
  - printenv RAILS_ENV

script:
- bundle exec rspec
- bundle exec codeclimate-test-reporter || true
