version: '2'

services:
  content-negotiation:
    image: crosscite/content-negotiation
    environment:
      - SEARCH_URL=https://search.test.datacite.org/
      - CITEPROC_URL="https://citation.test.datacite.org/format"
    build: .
    ports:
      - "8090:80"
    networks:
      - public
    volumes:
      - ./app:/home/app/webapp/app
      - ./config:/home/app/webapp/config
      - ./spec:/home/app/webapp/spec
  memcached:
    image: memcached:1.4.31
    networks:
      - public
networks:
  public:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.30.0/24
        gateway: 10.0.30.1
