version: '2'

services:
  content-negotiation:
    env_file:
      - .env
    image: crosscite/content-negotiation
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./spec:/home/app/webapp/spec
      - ./app:/home/app/webapp/app
