version: '2'

services:
  content-negotiation:
    image: crosscite/content-negotiation
    environment:
      - SANDBOX=1
      - SEARCH_URL=https://search.test.datacite.org/
    build: .
    ports:
      - "8090:80"
    volumes:
      - ./app:/home/app/webapp/app
      - ./config:/home/app/webapp/config
      - ./spec:/home/app/webapp/spec
  memcached:
    image: memcached:1.4.31
